### ISSUE TITLE
ASR 

### ISSUE THREAD

**Issue by wydwdy** [git-disl/Lockdown#1]
Thank you for providing the code, but I encountered a problem while running it. I hope you can help me solve it. I used the 'lockdown' method to run the 'fmnist' dataset according to your code, but the results were biased. The 'ASR' I obtained was as high as 50% and 60%, respectively, for both IID and non IID scenarios. May I ask if this result is reasonable, but I have run it multiple times and it has been the same result. What kind of modifications need to be made to the runtime of this dataset if it is unreasonable

**Comment by huangtiansheng** [comment]
For fashionMnist, the dense_ratio in the options.py should be set lower.  We recommend to use Cifar10 -resnet9 for default benchmark.  The default hyper-parameter should work for this dataset.

**Comment by wydwdy** [comment]
Thank you for your answer, it has been very helpful to me.
